// <auto-generated />
using System;
using CarRenter.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRenter.DB.Migrations
{
    [DbContext(typeof(CarRenterDbContext))]
    [Migration("20260824085531_SetsName")]
    partial class SetsName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRenter.DB.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CarRenter.DB.Models.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = "c1111111-1111-1111-1111-111111111111",
                            Brand = "Toyota",
                            Color = "Silver",
                            HourlyPrice = 12.50m,
                            Model = "Camry"
                        },
                        new
                        {
                            Id = "c2222222-2222-2222-2222-222222222222",
                            Brand = "Hyundai",
                            Color = "White",
                            HourlyPrice = 10.00m,
                            Model = "Elantra"
                        },
                        new
                        {
                            Id = "c3333333-3333-3333-3333-333333333333",
                            Brand = "Honda",
                            Color = "Black",
                            HourlyPrice = 11.00m,
                            Model = "Civic"
                        },
                        new
                        {
                            Id = "c4444444-4444-4444-4444-444444444444",
                            Brand = "BMW",
                            Color = "Dark Blue",
                            HourlyPrice = 28.00m,
                            Model = "Series 5"
                        },
                        new
                        {
                            Id = "c5555555-5555-5555-5555-555555555555",
                            Brand = "Mercedes-Benz",
                            Color = "Grey",
                            HourlyPrice = 30.00m,
                            Model = "C-Class"
                        },
                        new
                        {
                            Id = "c6666666-6666-6666-6666-666666666666",
                            Brand = "Kia",
                            Color = "Red",
                            HourlyPrice = 15.00m,
                            Model = "Sportage"
                        },
                        new
                        {
                            Id = "c7777777-7777-7777-7777-777777777777",
                            Brand = "Nissan",
                            Color = "White",
                            HourlyPrice = 14.50m,
                            Model = "Rogue"
                        },
                        new
                        {
                            Id = "c8888888-8888-8888-8888-888888888888",
                            Brand = "Ford",
                            Color = "Yellow",
                            HourlyPrice = 35.00m,
                            Model = "Mustang"
                        });
                });

            modelBuilder.Entity("CarRenter.DB.Models.Preference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreferenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preferences");

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            PreferenceName = "GPS Navigation System"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            PreferenceName = "Child Safety Seat"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            PreferenceName = "Full Coverage Insurance"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            PreferenceName = "Additional Driver"
                        },
                        new
                        {
                            Id = "55555555-5555-5555-5555-555555555555",
                            PreferenceName = "Wi-Fi Hotspot"
                        },
                        new
                        {
                            Id = "66666666-6666-6666-6666-666666666666",
                            PreferenceName = "Roadside Assistance"
                        },
                        new
                        {
                            Id = "77777777-7777-7777-7777-777777777777",
                            PreferenceName = "Roof Luggage Rack"
                        },
                        new
                        {
                            Id = "88888888-8888-8888-8888-888888888888",
                            PreferenceName = "Snow Chains / Winter Tires"
                        },
                        new
                        {
                            Id = "99999999-9999-9999-9999-999999999999",
                            PreferenceName = "Non-Smoking Vehicle"
                        },
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            PreferenceName = "Pet Friendly"
                        });
                });

            modelBuilder.Entity("CarRenter.DB.Models.Reservation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CarRenter.DB.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverLicenseNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PreferenceReservation", b =>
                {
                    b.Property<string>("PreferencesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReservationsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PreferencesId", "ReservationsId");

                    b.HasIndex("ReservationsId");

                    b.ToTable("ReservationPreferences", (string)null);
                });

            modelBuilder.Entity("CarRenter.DB.Models.Address", b =>
                {
                    b.HasOne("CarRenter.DB.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarRenter.DB.Models.Reservation", b =>
                {
                    b.HasOne("CarRenter.DB.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRenter.DB.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PreferenceReservation", b =>
                {
                    b.HasOne("CarRenter.DB.Models.Preference", null)
                        .WithMany()
                        .HasForeignKey("PreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRenter.DB.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRenter.DB.Models.Car", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CarRenter.DB.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
